### ISSUE TITLE
app breaks in firefox

### ISSUE THREAD

**Issue by rajchandra3** [devil-Coder/colors#20]
**Describe the bug**
Not working on Firefox (neither desktop nor mobile). The R, G, B is correctly shown, but the 6 colours below are left blank and, naturally, they don't respond to clicks.

**Screenshots**
![image](https://user-images.githubusercontent.com/25290995/78754714-97ace580-7995-11ea-85ac-0213b39d4fb2.png)

**Desktop (please complete the following information):**
 - OS: -
 - Browser: Firefox
 - Version: -

**Comment by gezeta-id** [comment]
OS is either Windows 10 or Linux, for desktop -I've tried both, it doesn't work in either- and for mobile is Firefox on Android. Versions are the latest stable ones for each system.

It looks like in the attached capture:

![Screenshot_2020-04-08 Color Tile by Raj Chandra](https://user-images.githubusercontent.com/20225121/78758698-d5524400-797e-11ea-9b68-dc7d9c286ef2.png)

In the console, there's this error:

```
TypeError: activeBorder[i] is undefined main.js:158:9
```

Correction to the initial comment: **As you can see in the capture, only R is shown correctly.**

----

The errors about Google Ads are more random.

**Comment by gezeta-id** [comment]
Ah. I've found the problem and your commit doesn't completely fix it.

You have 3 divs with the same `#activeBorder` id. This is wrong as the id should be _unique_ in the html. You need to remove those ids in the `index.html` and then to select by class `document.querySelectorAll('.active-border');` instead.

**Comment by rajchandra3** [comment]
yeah, you got this right. WIll fix it and push again.
